### ISSUE TITLE
Would you mind adding a README?

### ISSUE THREAD

**Issue by bmix** [ukuko/log4xslt#1]
Hello,

I am in need for logging of an XSLT. During research I found you mentioning it at https://stackoverflow.com/a/18689082/3795633.

Would you mind adding a little bit of a README to it, so one can get an overview and a little usage example? Can it report XML nodes or does it serialize everything to string? Just a few lines would totally be enough. Thanks.

**Comment by ukuko** [comment]
you are right. sorry, didnt get email before. just fixed.

**Comment by bmix** [comment]
Thanks!
